# Generated by Django 5.2.7 on 2025-10-05 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryBoy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keycloak_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                (
                    "current_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ASSIGNED", "Assigned"),
                            ("OUT_FOR_DELIVERY", "Out for Delivery"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                        ],
                        default="ASSIGNED",
                        max_length=20,
                    ),
                ),
                ("delivery_location", models.CharField(max_length=255)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order_app.order",
                    ),
                ),
                (
                    "delivery_boy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order_app.deliveryboy",
                    ),
                ),
            ],
        ),
    ]
